// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.11.2
// source: common_param.proto

package common_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ErrorResp) Reset() {
	*x = ErrorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_param_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResp) ProtoMessage() {}

func (x *ErrorResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_param_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResp.ProtoReflect.Descriptor instead.
func (*ErrorResp) Descriptor() ([]byte, []int) {
	return file_common_param_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// 心跳
type HeartbeatAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_param_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_common_param_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_common_param_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatAck) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// 连接成功
type ConnectionSuccessFromServerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID string `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
}

func (x *ConnectionSuccessFromServerResp) Reset() {
	*x = ConnectionSuccessFromServerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_param_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionSuccessFromServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionSuccessFromServerResp) ProtoMessage() {}

func (x *ConnectionSuccessFromServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_param_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionSuccessFromServerResp.ProtoReflect.Descriptor instead.
func (*ConnectionSuccessFromServerResp) Descriptor() ([]byte, []int) {
	return file_common_param_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionSuccessFromServerResp) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

// 登录
type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountType string `protobuf:"bytes,1,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Account     string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	EntityID    int64  `protobuf:"varint,3,opt,name=entityID,proto3" json:"entityID,omitempty"`
	ClientID    string `protobuf:"bytes,4,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Game        string `protobuf:"bytes,5,opt,name=game,proto3" json:"game,omitempty"`
	Region      int32  `protobuf:"varint,6,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_param_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_param_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_common_param_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReq) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *LoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginReq) GetEntityID() int64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *LoginReq) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *LoginReq) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *LoginReq) GetRegion() int32 {
	if x != nil {
		return x.Region
	}
	return 0
}

type LoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID int64  `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	Game     string `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	Region   int32  `protobuf:"varint,3,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_param_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_param_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_common_param_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResp) GetEntityID() int64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *LoginResp) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *LoginResp) GetRegion() int32 {
	if x != nil {
		return x.Region
	}
	return 0
}

// 网关广播消息
type GateBroadcastMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GateBroadcastMsg) Reset() {
	*x = GateBroadcastMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_param_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateBroadcastMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateBroadcastMsg) ProtoMessage() {}

func (x *GateBroadcastMsg) ProtoReflect() protoreflect.Message {
	mi := &file_common_param_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateBroadcastMsg.ProtoReflect.Descriptor instead.
func (*GateBroadcastMsg) Descriptor() ([]byte, []int) {
	return file_common_param_proto_rawDescGZIP(), []int{5}
}

func (x *GateBroadcastMsg) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GateBroadcastMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 加入场景
type JoinSceneReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneType string `protobuf:"bytes,1,opt,name=sceneType,proto3" json:"sceneType,omitempty"`
	SceneID   int64  `protobuf:"varint,2,opt,name=sceneID,proto3" json:"sceneID,omitempty"`
}

func (x *JoinSceneReq) Reset() {
	*x = JoinSceneReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_param_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinSceneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSceneReq) ProtoMessage() {}

func (x *JoinSceneReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_param_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSceneReq.ProtoReflect.Descriptor instead.
func (*JoinSceneReq) Descriptor() ([]byte, []int) {
	return file_common_param_proto_rawDescGZIP(), []int{6}
}

func (x *JoinSceneReq) GetSceneType() string {
	if x != nil {
		return x.SceneType
	}
	return ""
}

func (x *JoinSceneReq) GetSceneID() int64 {
	if x != nil {
		return x.SceneID
	}
	return 0
}

type JoinSceneResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneType string `protobuf:"bytes,1,opt,name=sceneType,proto3" json:"sceneType,omitempty"`
	SceneID   int64  `protobuf:"varint,2,opt,name=sceneID,proto3" json:"sceneID,omitempty"`
}

func (x *JoinSceneResp) Reset() {
	*x = JoinSceneResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_param_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinSceneResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSceneResp) ProtoMessage() {}

func (x *JoinSceneResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_param_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSceneResp.ProtoReflect.Descriptor instead.
func (*JoinSceneResp) Descriptor() ([]byte, []int) {
	return file_common_param_proto_rawDescGZIP(), []int{7}
}

func (x *JoinSceneResp) GetSceneType() string {
	if x != nil {
		return x.SceneType
	}
	return ""
}

func (x *JoinSceneResp) GetSceneID() int64 {
	if x != nil {
		return x.SceneID
	}
	return 0
}

// 离开场景
type LeaveSceneReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneType string `protobuf:"bytes,1,opt,name=sceneType,proto3" json:"sceneType,omitempty"`
	SceneID   int64  `protobuf:"varint,2,opt,name=sceneID,proto3" json:"sceneID,omitempty"`
}

func (x *LeaveSceneReq) Reset() {
	*x = LeaveSceneReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_param_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveSceneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSceneReq) ProtoMessage() {}

func (x *LeaveSceneReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_param_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSceneReq.ProtoReflect.Descriptor instead.
func (*LeaveSceneReq) Descriptor() ([]byte, []int) {
	return file_common_param_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveSceneReq) GetSceneType() string {
	if x != nil {
		return x.SceneType
	}
	return ""
}

func (x *LeaveSceneReq) GetSceneID() int64 {
	if x != nil {
		return x.SceneID
	}
	return 0
}

type LeaveSceneResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneType string `protobuf:"bytes,1,opt,name=sceneType,proto3" json:"sceneType,omitempty"`
	SceneID   int64  `protobuf:"varint,2,opt,name=sceneID,proto3" json:"sceneID,omitempty"`
}

func (x *LeaveSceneResp) Reset() {
	*x = LeaveSceneResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_param_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveSceneResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSceneResp) ProtoMessage() {}

func (x *LeaveSceneResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_param_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSceneResp.ProtoReflect.Descriptor instead.
func (*LeaveSceneResp) Descriptor() ([]byte, []int) {
	return file_common_param_proto_rawDescGZIP(), []int{9}
}

func (x *LeaveSceneResp) GetSceneType() string {
	if x != nil {
		return x.SceneType
	}
	return ""
}

func (x *LeaveSceneResp) GetSceneID() int64 {
	if x != nil {
		return x.SceneID
	}
	return 0
}

// =========多人AOI============
// 创建角色
type OnCreateEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID int64   `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	Type     string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	X        float32 `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y        float32 `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Z        float32 `protobuf:"fixed32,5,opt,name=z,proto3" json:"z,omitempty"`
	Yaw      float32 `protobuf:"fixed32,6,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Speed    float32 `protobuf:"fixed32,7,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *OnCreateEntity) Reset() {
	*x = OnCreateEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_param_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnCreateEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnCreateEntity) ProtoMessage() {}

func (x *OnCreateEntity) ProtoReflect() protoreflect.Message {
	mi := &file_common_param_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnCreateEntity.ProtoReflect.Descriptor instead.
func (*OnCreateEntity) Descriptor() ([]byte, []int) {
	return file_common_param_proto_rawDescGZIP(), []int{10}
}

func (x *OnCreateEntity) GetEntityID() int64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *OnCreateEntity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OnCreateEntity) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *OnCreateEntity) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *OnCreateEntity) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *OnCreateEntity) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *OnCreateEntity) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

// 销毁角色
type OnDestroyEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID int64 `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
}

func (x *OnDestroyEntity) Reset() {
	*x = OnDestroyEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_param_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnDestroyEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnDestroyEntity) ProtoMessage() {}

func (x *OnDestroyEntity) ProtoReflect() protoreflect.Message {
	mi := &file_common_param_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnDestroyEntity.ProtoReflect.Descriptor instead.
func (*OnDestroyEntity) Descriptor() ([]byte, []int) {
	return file_common_param_proto_rawDescGZIP(), []int{11}
}

func (x *OnDestroyEntity) GetEntityID() int64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

// AOI同步信息
type AOISyncInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID int64   `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	X        float32 `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y        float32 `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z        float32 `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	Yaw      float32 `protobuf:"fixed32,5,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Speed    float32 `protobuf:"fixed32,6,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *AOISyncInfo) Reset() {
	*x = AOISyncInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_param_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AOISyncInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AOISyncInfo) ProtoMessage() {}

func (x *AOISyncInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_param_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AOISyncInfo.ProtoReflect.Descriptor instead.
func (*AOISyncInfo) Descriptor() ([]byte, []int) {
	return file_common_param_proto_rawDescGZIP(), []int{12}
}

func (x *AOISyncInfo) GetEntityID() int64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *AOISyncInfo) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AOISyncInfo) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *AOISyncInfo) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *AOISyncInfo) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *AOISyncInfo) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type AOISyncInfoBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SyncInfos []*AOISyncInfo `protobuf:"bytes,1,rep,name=syncInfos,proto3" json:"syncInfos,omitempty"`
}

func (x *AOISyncInfoBatch) Reset() {
	*x = AOISyncInfoBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_param_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AOISyncInfoBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AOISyncInfoBatch) ProtoMessage() {}

func (x *AOISyncInfoBatch) ProtoReflect() protoreflect.Message {
	mi := &file_common_param_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AOISyncInfoBatch.ProtoReflect.Descriptor instead.
func (*AOISyncInfoBatch) Descriptor() ([]byte, []int) {
	return file_common_param_proto_rawDescGZIP(), []int{13}
}

func (x *AOISyncInfoBatch) GetSyncInfos() []*AOISyncInfo {
	if x != nil {
		return x.SyncInfos
	}
	return nil
}

// 移动
type MoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X     float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y     float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z     float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Yaw   float32 `protobuf:"fixed32,4,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Speed float32 `protobuf:"fixed32,5,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *MoveReq) Reset() {
	*x = MoveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_param_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveReq) ProtoMessage() {}

func (x *MoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_param_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveReq.ProtoReflect.Descriptor instead.
func (*MoveReq) Descriptor() ([]byte, []int) {
	return file_common_param_proto_rawDescGZIP(), []int{14}
}

func (x *MoveReq) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveReq) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MoveReq) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *MoveReq) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *MoveReq) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

var File_common_param_proto protoreflect.FileDescriptor

var file_common_param_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x33, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x22, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x1f, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x46, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0xaa, 0x01, 0x0a, 0x08, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x67,
	0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0x53, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x67, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0x3a, 0x0a, 0x10,
	0x47, 0x61, 0x74, 0x65, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4d, 0x73, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x46, 0x0a, 0x0c, 0x4a, 0x6f, 0x69, 0x6e,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x63, 0x65, 0x6e,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x44,
	0x22, 0x47, 0x0a, 0x0d, 0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x44, 0x22, 0x47, 0x0a, 0x0d, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x63,
	0x65, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e,
	0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65,
	0x49, 0x44, 0x22, 0x48, 0x0a, 0x0e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x44, 0x22, 0x92, 0x01, 0x0a,
	0x0e, 0x4f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x10, 0x0a, 0x03, 0x79, 0x61, 0x77,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x79, 0x61, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x70, 0x65, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65,
	0x64, 0x22, 0x2d, 0x0a, 0x0f, 0x4f, 0x6e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44,
	0x22, 0x7b, 0x0a, 0x0b, 0x41, 0x4f, 0x49, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x10, 0x0a, 0x03, 0x79, 0x61, 0x77, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x03, 0x79, 0x61, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x22, 0x4b, 0x0a,
	0x10, 0x41, 0x4f, 0x49, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x37, 0x0a, 0x09, 0x73, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x4f, 0x49, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x09, 0x73, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x5b, 0x0a, 0x07, 0x4d, 0x6f,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01,
	0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x12,
	0x10, 0x0a, 0x03, 0x79, 0x61, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x79, 0x61,
	0x77, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x42, 0x0f, 0x5a, 0x0d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_param_proto_rawDescOnce sync.Once
	file_common_param_proto_rawDescData = file_common_param_proto_rawDesc
)

func file_common_param_proto_rawDescGZIP() []byte {
	file_common_param_proto_rawDescOnce.Do(func() {
		file_common_param_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_param_proto_rawDescData)
	})
	return file_common_param_proto_rawDescData
}

var file_common_param_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_common_param_proto_goTypes = []interface{}{
	(*ErrorResp)(nil),                       // 0: common_proto.ErrorResp
	(*HeartbeatAck)(nil),                    // 1: common_proto.HeartbeatAck
	(*ConnectionSuccessFromServerResp)(nil), // 2: common_proto.ConnectionSuccessFromServerResp
	(*LoginReq)(nil),                        // 3: common_proto.LoginReq
	(*LoginResp)(nil),                       // 4: common_proto.LoginResp
	(*GateBroadcastMsg)(nil),                // 5: common_proto.GateBroadcastMsg
	(*JoinSceneReq)(nil),                    // 6: common_proto.JoinSceneReq
	(*JoinSceneResp)(nil),                   // 7: common_proto.JoinSceneResp
	(*LeaveSceneReq)(nil),                   // 8: common_proto.LeaveSceneReq
	(*LeaveSceneResp)(nil),                  // 9: common_proto.LeaveSceneResp
	(*OnCreateEntity)(nil),                  // 10: common_proto.OnCreateEntity
	(*OnDestroyEntity)(nil),                 // 11: common_proto.OnDestroyEntity
	(*AOISyncInfo)(nil),                     // 12: common_proto.AOISyncInfo
	(*AOISyncInfoBatch)(nil),                // 13: common_proto.AOISyncInfoBatch
	(*MoveReq)(nil),                         // 14: common_proto.MoveReq
}
var file_common_param_proto_depIdxs = []int32{
	12, // 0: common_proto.AOISyncInfoBatch.syncInfos:type_name -> common_proto.AOISyncInfo
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_common_param_proto_init() }
func file_common_param_proto_init() {
	if File_common_param_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_param_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_param_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_param_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionSuccessFromServerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_param_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_param_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_param_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateBroadcastMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_param_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinSceneReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_param_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinSceneResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_param_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveSceneReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_param_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveSceneResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_param_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnCreateEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_param_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnDestroyEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_param_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AOISyncInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_param_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AOISyncInfoBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_param_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_param_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_param_proto_goTypes,
		DependencyIndexes: file_common_param_proto_depIdxs,
		MessageInfos:      file_common_param_proto_msgTypes,
	}.Build()
	File_common_param_proto = out.File
	file_common_param_proto_rawDesc = nil
	file_common_param_proto_goTypes = nil
	file_common_param_proto_depIdxs = nil
}
