// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.11.2
// source: framework.proto

package common_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameDispatcherChannelInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateClusterID int32  `protobuf:"varint,1,opt,name=gateClusterID,proto3" json:"gateClusterID,omitempty"`
	Game          string `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	GameClusterID int32  `protobuf:"varint,3,opt,name=gameClusterID,proto3" json:"gameClusterID,omitempty"`
	ChannelID     int32  `protobuf:"varint,4,opt,name=channelID,proto3" json:"channelID,omitempty"`
}

func (x *GameDispatcherChannelInfoReq) Reset() {
	*x = GameDispatcherChannelInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_framework_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameDispatcherChannelInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDispatcherChannelInfoReq) ProtoMessage() {}

func (x *GameDispatcherChannelInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_framework_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDispatcherChannelInfoReq.ProtoReflect.Descriptor instead.
func (*GameDispatcherChannelInfoReq) Descriptor() ([]byte, []int) {
	return file_framework_proto_rawDescGZIP(), []int{0}
}

func (x *GameDispatcherChannelInfoReq) GetGateClusterID() int32 {
	if x != nil {
		return x.GateClusterID
	}
	return 0
}

func (x *GameDispatcherChannelInfoReq) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *GameDispatcherChannelInfoReq) GetGameClusterID() int32 {
	if x != nil {
		return x.GameClusterID
	}
	return 0
}

func (x *GameDispatcherChannelInfoReq) GetChannelID() int32 {
	if x != nil {
		return x.ChannelID
	}
	return 0
}

type GameDispatcherChannelInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GameDispatcherChannelInfoResp) Reset() {
	*x = GameDispatcherChannelInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_framework_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameDispatcherChannelInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDispatcherChannelInfoResp) ProtoMessage() {}

func (x *GameDispatcherChannelInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_framework_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDispatcherChannelInfoResp.ProtoReflect.Descriptor instead.
func (*GameDispatcherChannelInfoResp) Descriptor() ([]byte, []int) {
	return file_framework_proto_rawDescGZIP(), []int{1}
}

func (x *GameDispatcherChannelInfoResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GameDispatcherChannelInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type NewPlayerConnectionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID int64 `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	Region   int32 `protobuf:"varint,2,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *NewPlayerConnectionReq) Reset() {
	*x = NewPlayerConnectionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_framework_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewPlayerConnectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPlayerConnectionReq) ProtoMessage() {}

func (x *NewPlayerConnectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_framework_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPlayerConnectionReq.ProtoReflect.Descriptor instead.
func (*NewPlayerConnectionReq) Descriptor() ([]byte, []int) {
	return file_framework_proto_rawDescGZIP(), []int{2}
}

func (x *NewPlayerConnectionReq) GetEntityID() int64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *NewPlayerConnectionReq) GetRegion() int32 {
	if x != nil {
		return x.Region
	}
	return 0
}

type PlayerDisconnectedReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID int64 `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
}

func (x *PlayerDisconnectedReq) Reset() {
	*x = PlayerDisconnectedReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_framework_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerDisconnectedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDisconnectedReq) ProtoMessage() {}

func (x *PlayerDisconnectedReq) ProtoReflect() protoreflect.Message {
	mi := &file_framework_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDisconnectedReq.ProtoReflect.Descriptor instead.
func (*PlayerDisconnectedReq) Descriptor() ([]byte, []int) {
	return file_framework_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerDisconnectedReq) GetEntityID() int64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

var File_framework_proto protoreflect.FileDescriptor

var file_framework_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x9c, 0x01, 0x0a, 0x1c, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x12, 0x24, 0x0a, 0x0d, 0x67, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x67, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x67, 0x61,
	0x6d, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x22, 0x4b,
	0x0a, 0x1d, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x4c, 0x0a, 0x16, 0x4e,
	0x65, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0x33, 0x0a, 0x15, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x42, 0x0f,
	0x5a, 0x0d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_framework_proto_rawDescOnce sync.Once
	file_framework_proto_rawDescData = file_framework_proto_rawDesc
)

func file_framework_proto_rawDescGZIP() []byte {
	file_framework_proto_rawDescOnce.Do(func() {
		file_framework_proto_rawDescData = protoimpl.X.CompressGZIP(file_framework_proto_rawDescData)
	})
	return file_framework_proto_rawDescData
}

var file_framework_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_framework_proto_goTypes = []interface{}{
	(*GameDispatcherChannelInfoReq)(nil),  // 0: common_proto.GameDispatcherChannelInfoReq
	(*GameDispatcherChannelInfoResp)(nil), // 1: common_proto.GameDispatcherChannelInfoResp
	(*NewPlayerConnectionReq)(nil),        // 2: common_proto.NewPlayerConnectionReq
	(*PlayerDisconnectedReq)(nil),         // 3: common_proto.PlayerDisconnectedReq
}
var file_framework_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_framework_proto_init() }
func file_framework_proto_init() {
	if File_framework_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_framework_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameDispatcherChannelInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_framework_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameDispatcherChannelInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_framework_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewPlayerConnectionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_framework_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerDisconnectedReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_framework_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_framework_proto_goTypes,
		DependencyIndexes: file_framework_proto_depIdxs,
		MessageInfos:      file_framework_proto_msgTypes,
	}.Build()
	File_framework_proto = out.File
	file_framework_proto_rawDesc = nil
	file_framework_proto_goTypes = nil
	file_framework_proto_depIdxs = nil
}
